version: 0.1

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python ./build.py
  post_build:
    commands:
      - bash ./deploy.sh

artifacts:
  type: NONE
  files:
    - dist/*
  discard-paths: yes
